GET http://localhost:3000/v1/posts
###

POST http://localhost:3000/v1/posts
Content-Type: application/json

{
    "title": "How to vibecode?",
    "author": "Jaden Navis",
    "url": "http://example.app.com/jaden-navis"
}
###

GET http://localhost:3000/v1/posts/6a4fd4a6a717503f88b333db
###

POST http://localhost:3000/v1/posts/6a4fd4a6a717503f88b333db/like
Content-Type: application/json

{
    "userId": "6a4fd4a6a717503f88b333db"
}
###
